# Generated by Django 2.2.6 on 2019-11-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MenuSelection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THRUSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=10)),
                ('type', models.CharField(choices=[('BREAKFAST', 'BREAKFAST'), ('LUNCH', 'LUNCH'), ('EVENING SNACKS & DINNER', 'EVENING SNACKS & DINNER'), ('SPECIAL ITEMS', 'SPECIAL ITEMS')], max_length=30)),
                ('quantiy', models.PositiveIntegerField()),
                ('quantiy_of_measurement', models.CharField(choices=[('Kg', 'Kg'), ('Grams', 'Grams'), ('Litre', 'Litre')], max_length=10)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MenuSelection.MenuMaster')),
            ],
        ),
    ]
