# Generated by Django 2.2.6 on 2019-11-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuSelection', '0002_menuselection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuselection',
            name='item_name',
        ),
        migrations.DeleteModel(
            name='MenuMaster',
        ),
        migrations.DeleteModel(
            name='MenuSelection',
        ),
    ]
