# Generated by Django 2.2.6 on 2019-11-21 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MenuSelection', '0004_menumaster_menuselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceipeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_quantity', models.PositiveIntegerField()),
                ('base_uom', models.CharField(choices=[('Kg', 'Kg'), ('Grams', 'Grams'), ('Litre', 'Litre')], max_length=10)),
                ('item', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=20)),
                ('measure', models.PositiveIntegerField()),
                ('unit_of_measure', models.CharField(choices=[('Kg', 'Kg'), ('Grams', 'Grams'), ('Litre', 'Litre')], max_length=10)),
                ('factor', models.FloatField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MenuSelection.MenuMaster')),
            ],
        ),
    ]
