# Generated by Django 2.2.6 on 2019-11-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuSelection', '0006_auto_20191121_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipemaster',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='receipemaster',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
