# Generated by Django 2.2.6 on 2019-11-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuSelection', '0007_auto_20191121_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuselection',
            name='quantiy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='receipemaster',
            name='base_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='receipemaster',
            name='measure',
            field=models.IntegerField(),
        ),
    ]
