# Generated by Django 2.2.6 on 2019-11-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuSelection', '0009_auto_20191121_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuselection',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
