# Generated by Django 2.2.6 on 2019-11-21 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MenuSelection', '0011_auto_20191121_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumaster',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
