# Generated by Django 2.2.6 on 2019-11-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuSelection', '0012_menumaster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumaster',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
