# Generated by Django 2.2.6 on 2019-11-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuSelection', '0013_auto_20191121_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumaster',
            name='type',
            field=models.CharField(choices=[('BREAKFAST', 'BREAKFAST'), ('LUNCH', 'LUNCH'), ('EVENING SNACKS & DINNER', 'EVENING SNACKS & DINNER'), ('SPECIAL ITEMS', 'SPECIAL ITEMS')], default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menumaster',
            name='image',
            field=models.ImageField(blank=True, upload_to='item'),
        ),
    ]
