# Generated by Django 2.2.6 on 2019-11-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuSelection', '0014_auto_20191121_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuselection',
            name='quantiy_of_measurement',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='receipemaster',
            name='base_uom',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='receipemaster',
            name='unit_of_measure',
            field=models.CharField(max_length=10),
        ),
    ]
